### ISSUE TITLE
链接提取后文本剔除问题

### ISSUE THREAD

**Issue by longli928** [lz233/Tarnhelm#11]
问题背景：文档-指南 部分中提到：根据内置正则表达式从中提取出链接。
但在使用中例如接收到文本：
`分享46_P/诗岸的单曲《Narcissus》: https://y.music.163.com/m/song?id=1835695995&userid=299866209&dlt=0846 (来自@网易云音乐)` 
处理后为：
`分享46_P/诗岸的单曲《Narcissus》: https://y.music.163.com/m/song?id=1835695995 (来自@网易云音乐)` 
链接前后的文本没有剔除；
我自己写的正则 `\s|(.+(?=http))|(\?.*)`
接收到的文本：
`花栗鼠的颊囊可以塞进多少橡子 UP主: 央视纪录 http://www.bilibili.com/video/av644541079?share_medium=android&share_source=more&bbid=XZEE1D4E6E110016EE6A04C131A178B148E64&ts=1660686643527` 
本应该将http前面的视频标题去掉，但是处理后的结果是：
`花栗鼠的颊囊可以塞进多少橡子 UP主: 央视纪录 http://www.bilibili.com/video/av644541079` 
是否是我正则写的有问题

**Comment by lz233** [comment]
文档忘改了...
由于 binder 的大小限制，Tarnhelm 仅会提取文本中的链接进行处理，其他部分不会进入处理流程
