### ISSUE TITLE
Use Shizuku to Enable Background Function?

### ISSUE THREAD

**Issue by Jvcon** [lz233/Tarnhelm#15]
开启后台监听模式需要通过adb来激活，是否考虑增加Shizuku来开启这一模式？（不过我不太熟悉安卓开发，只是看起来Shizuku可以调用adb的pm命令，Tarnhelm开启监听模式也有用到adb pm命令，不知道是否有可行性）

https://github.com/RikkaApps/Shizuku/blob/master/README.md

**Comment by lz233** [comment]
我认为没必要。因为这是一次性的操作。
