### ISSUE TITLE
Incorrect parsing of the Telegram invitation link

### ISSUE THREAD

**Issue by omg-xtao** [lz233/Tarnhelm#24]
Example: `https://t.me/+ABC`
Copied as: `https://t.me/ ABC`

https://github.com/lz233/Tarnhelm/blob/8825c68e5af9484c8c63287ee44a522cc9b69d7b/app/src/main/java/cn/ac/lz233/tarnhelm/util/ktx/String.kt#L66

Temporary remedies: `eyJhIjoidGciLCJiIjpbInQubWVcLyAiXSwiYyI6WyJ0Lm1lXC8rIl0sImQiOiJvbWcteHRhbyJ9`

**Comment by lz233** [comment]
Because some apps will directly connect URLs and characters without spacing, like `https://xxxxxxx(来自@xxxx)`, so we must do `decodeURL()` since okhttp will automatically encode it.
If ignoring the irregularity, we can remove this behavior.

**Comment by lz233** [comment]
So I have no idea at this time(

**Comment by omg-xtao** [comment]
~

**Comment by lz233** [comment]
It is an obvious problem and should not be closed

**Comment by lz233** [comment]
Fixed in [1.5.4](https://github.com/lz233/Tarnhelm/releases/tag/20230925) and will be published in Google Play later. Please tell me if the problem still occur.
