### ISSUE TITLE
网址提取规则该怎么填

### ISSUE THREAD

**Issue by zyh941** [lz233/Tarnhelm#26]
你好开发者，我最近遇到了这种带中文的网址，试了正则和参数，都无法把多余的部分清除，不知有没有合适的方法？示例网址（text=后面就是中文，但其实提取到#前就可以正常访问了，不含#）：
https://zhuanlan.zhihu.com/p/537022236#:~:text=%E6%A0%B9%E6%8D%AE%E3%80%8A%E4%BA%BA%E6%B0%91%E8%AD%A6%E5%AF%9F%E6%B3%95,%E4%BB%A5%E5%AE%9E%E8%A1%8C%E4%BA%A4%E9%80%9A%E7%AE%A1%E5%88%B6%E3%80%82

**Comment by lz233** [comment]
tarnhelm://rule?regex=eyJhIjoidGVzdCIsImIiOlsiIy4qIl0sImMiOlsiIl0sImQiOiJsejIzMyJ9
