### ISSUE TITLE
how to use[clear step by step instruction]

### ISSUE THREAD

**Issue by Tanzin01** [lz233/Tarnhelm#29]

**Comment by lz233** [comment]
Simply it is the basic usage of this app:

https://user-images.githubusercontent.com/32504382/209994025-06f67d46-c011-4a47-9fa9-f16c8141d002.mp4

For detailed usage, see the [document](https://tranhelm.project.ac.cn) is a better way, but I have not written an English one yet, maybe you can read it with Google Translate. (>.<)

When English version is available, I will comment below.

**Comment by Tanzin01** [comment]
Got it! So i need to click "triple dot" to get  tarnhelm options!

almost a month since i installed tarnhelm. Read the translated documentation 3 or 4 times(transaltion was good) but missed this critical point. did ggl search but irrelevent results! 
[i used to thought tarnhelm auto-modify url, whenever someone copy a url. i guess i should stop assuming things!][also no need to invest time in translating to english, i think. Just add the above video or its url in documentaion. it should be enough for other too, like me]

Good application :)

**Comment by lz233** [comment]
In fact, Tarnhelm can auto-modify urls after copying.
![Screenshot_20221230-145525~2](https://user-images.githubusercontent.com/32504382/210043167-3a6942da-410c-4370-8d94-8e924cfdb94b.png)

**Comment by lz233** [comment]
English version is available: https://tarnhelm.project.ac.cn/en/

**Comment by Tanzin01** [comment]
Cool
