### ISSUE TITLE
覆写剪贴板悬浮窗失效

### ISSUE THREAD

**Issue by Lightsummer233** [lz233/Tarnhelm#33]
[LSPosed_2023-04-22T10_19_20.942604.zip](https://github.com/lz233/Tarnhelm/files/11300059/LSPosed_2023-04-22T10_19_20.942604.zip)
[系统界面-13(33).zip](https://github.com/lz233/Tarnhelm/files/11300061/-13.33.zip)
Log 以及系统界面安装包，不出意外是方法改了导致的。
希望修复（）

**Comment by lz233** [comment]
系统版本（精确到版本号）？

**Comment by Lightsummer233** [comment]
![Screenshot_20230422-102442_设置](https://user-images.githubusercontent.com/93428659/233757056-dac1bb05-f8c7-4a07-8c2e-09165a4042dd.png)

**Comment by Lightsummer233** [comment]
有办法测试吗？

**Comment by lz233** [comment]
pixel用的是新的，那我不管旧的了

**Comment by lz233** [comment]
[app-github-release.apk.zip](https://github.com/lz233/Tarnhelm/files/11311684/app-github-release.apk.zip)

测试一下，没问题我发版。

我发现即使是同一 build id，这块代码也不一样。

**Comment by Lightsummer233** [comment]
还是不行。。

**Comment by Lightsummer233** [comment]
不过没有之前找不到方法的日志了。

**Comment by lz233** [comment]
> 不过没有之前找不到方法的日志了。

看下其他日志？

**Comment by Lightsummer233** [comment]
放tg群组了。
