### ISSUE TITLE
Plus is replaced with space even when no rules are triggered

### ISSUE THREAD

**Issue by cloudrac3r** [lz233/Tarnhelm#37]
Steps to reproduce:

1. Enable any Tarnhelm replacement method (e.g. Xposed rewrite clipboard)
2. Turn off all rules (this shows that it isn't a problem from a custom rule)
3. Copy this: https://a.com/a+a+a
4. Paste it, now plus has been replaced with space and it says: https://a.com/a a a

This breaks links such as https://www.wolframalpha.com/input?i=how+popular+was+the+name+Bella+when+Twilight+came+out%3F because the plus is required for the URL.

Ideally, plus should stay as plus and not be replaced.

Thanks for the awesome app, and please let me know if you need any more info to fix this! <3

**Comment by omg-xtao** [comment]
#24

**Comment by lz233** [comment]
Fixed in [1.5.4](https://github.com/lz233/Tarnhelm/releases/tag/20230925) and will be published in Google Play later. Please tell me if the problem still occur.

**Comment by cloudrac3r** [comment]
It seems good to me now, thank you very much! :)
