### ISSUE TITLE
响应 `tarnhelm://` 链接跳转

### ISSUE THREAD

**Issue by Bluemangoo** [lz233/Tarnhelm#39]
将 Tarnhelm 注册为 `tarnhelm://` 的打开方式，可以快捷添加规则。添加完毕后弹窗反馈（或类似于一个木函的复制分享文本的反馈）

**Comment by lz233** [comment]
已经实现的功能。
在 https://tarnhelm.project.ac.cn/rules.html 点击相关标题即可添加。
如果在你的设备上不工作，请更换为 chrome 浏览器
