### ISSUE TITLE
Share dialog not working

### ISSUE THREAD

**Issue by Webpage-gh** [lz233/Tarnhelm#41]
您好，Tarmhelm的分享对话框模式没有生效，在Tarnhelm弹出分享对话框，然后选择应用后对话框消失，没有打开要目标应用
复现步骤：在任意应用中分享-选择Tarnhelm-在第二次弹出的分享对话框中选择任意应用

Android版本：13
MIUI版本：MIUI Global 14.0.2.0(TGBINXM)
测试过的Tarnhelm版本：1.5.4和1.5.5

**Comment by lz233** [comment]
检查miui是否进行了拦截

**Comment by Webpage-gh** [comment]
看起来是MIUI14的锅了，我没有办法找到错误的原因，它在Color OS上是正常的

**Comment by lz233** [comment]
@Webpage-gh 在miui的应用行为里应该可以看到

**Comment by Webpage-gh** [comment]
这个问题在国内版和国际版的MIUI14上都有，其他版本就不知道了。国内版的应用行为记录里和软件有关的只有MT尝试打开Tarnhelm的记录，__没有发现和剪切板、分享有关的记录__。请问还可以从哪方面入手来调查问题？

**Comment by Webpage-gh** [comment]
这个问题似乎是因为MIUI定制分享对话框造成的，在我使用Island创建工作资料后，Tarnhelm就能正常工作了。第一次创建工作资料后没有显示第二个分享对话框，不过重启后就正常了。
因此如果MIUI出现了类似的问题，可以尝试使用Island创建工作资料并重启设备，有可能会解决这个问题
