### ISSUE TITLE
通过Android 14系统分享菜单复制到剪贴板不会触发Tarnhelm

### ISSUE THREAD

**Issue by Mosney** [lz233/Tarnhelm#42]
任意链接通过**分享菜单**右侧的**复制按钮**复制到剪贴板，不会触发Tarnhelm处理。
例如下图，点击YouTube视频下方的分享按钮会调用系统分享菜单，再点击右侧复制按钮，会复制到带追踪参数的URL。
而直接使用复制菜单复制到剪贴板的URL会被正常处理掉追踪参数。
![图片](https://github.com/lz233/Tarnhelm/assets/22477230/5bc66c79-a8b4-43bb-b89e-4c0f7ed3944d)

另外测试在Pixel短信应用中也是相同的结果，直接复制可以被正常处理，如果选择使用分享菜单再复制的话就不会被Tarnhelm处理

**Comment by lz233** [comment]
不好意思，之前没想明白，但其实你再点一次 tarnhelm 图标不就会弹出一个一模一样的弹窗，但是是处理后的链接吗
所以这似乎没问题

<img width="1360" alt="image" src="https://github.com/lz233/Tarnhelm/assets/32504382/c2b1971a-00f8-4e54-93db-e6f5b95ef75a">
