### ISSUE TITLE
许愿新功能-分享链接到粘贴板

### ISSUE THREAD

**Issue by 3049298988** [lz233/Tarnhelm#48]
如题
触发分享菜单时，希望可以选择Tarnhelm
经过其处理后再复制到粘贴板

**Comment by lz233** [comment]
已经有了，从系统的剪切板浮窗里点击就是


https://github.com/lz233/Tarnhelm/assets/32504382/7ef91d80-36ea-4f90-bbda-b82c967a6de1

**Comment by 3049298988** [comment]
> 已经有了，从系统的剪切板浮窗里点击就是
> 
>  screen-20240425-132130.mp4

对于（类）原生系统来说确实有了，不过其他无法调出原生粘贴板的系统还是有些尴尬

**Comment by lz233** [comment]
并不打算对国产 ROM 进行适配。顺带一提，MIUI 是可以把弹窗重新打开的，有人做了模块
