### ISSUE TITLE
 重定向规则超时

### ISSUE THREAD

**Issue by Bluemangoo** [lz233/Tarnhelm#55]
简单调试了一下，应该是这一行报错直接跳过后续逻辑了。这行删掉就正常了。要不这里做个判断而不是去提取默认头吧。

https://github.com/lz233/Tarnhelm/blob/a1eba9fef2bfa5d8d98bb1f0351a83348744224c/app/src/main/java/cn/ac/lz233/tarnhelm/util/ktx/OkHttp.kt#L18

**Comment by lz233** [comment]
@Bluemangoo 看一下报错？
这行没涉及到网络，感觉很奇怪

**Comment by Bluemangoo** [comment]
我没看到报错，它是直接跳走了。

**Comment by Bluemangoo** [comment]
调试到这里就直接卡死了。

**Comment by Bluemangoo** [comment]
3 days ping

**Comment by lz233** [comment]
没日志我无从下手

**Comment by Bluemangoo** [comment]
它真的没有日志输出啊。

**Comment by Bluemangoo** [comment]
细看了一下，只要填了用户代理就是正常的，怀疑是 `WebSettings.getDefaultUserAgent(App.context)` 的问题。

**Comment by Bluemangoo** [comment]
找了些办法输出，是正常的UA。

**Comment by lz233** [comment]
@Bluemangoo 那应该没问题啊 我觉得只可能是目标网站碰到这个UA就不工作

**Comment by Bluemangoo** [comment]
我把UA设置成这个也是正常的。

**Comment by Bluemangoo** [comment]
想不通了。

**Comment by Bluemangoo** [comment]
`Mozilla/5.0 (Linux; Android 14; V2307A Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36`
