### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by iBye2mass** [lz233/Tarnhelm#59]
A14 s23+ oneui6.1.1 lsp1.10.1(7125)
![Screenshot_20241125_031136_Shell](https://github.com/user-attachments/assets/98a38b94-0759-4f38-b4a0-0a341c2e3b9f)
![Screenshot_20241125_031154_Shell](https://github.com/user-attachments/assets/9cca9927-2852-4517-ab47-74bffb81a7e5)

**Comment by lz233** [comment]
首先，我不觉得 oneui 有剪切板悬浮窗，这是为原生系统设计的。如果有，请告诉我。

**Comment by iBye2mass** [comment]
感谢
