### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [lz233/Tarnhelm#6]
请问可以将应用发布到 F-Droid 吗？

**Comment by lz233** [comment]
目前还没有完工，等完工之后会通知你
Play的版本是带遥测的，现在也有计划实现FOSS版，还没做

**Comment by linsui** [comment]
谢谢！

**Comment by linsui** [comment]
请问可以打个 tag 吗？我们需要 tag 进行自动更新。

**Comment by lz233** [comment]
> 请问可以打个 tag 吗？我们需要 tag 进行自动更新。

好

**Comment by linsui** [comment]
只要有新版本的时候发布新 tag 就行。请在 tag 中包含 version code，否则我们获取不到。谢谢

**Comment by lz233** [comment]
好

**Comment by linsui** [comment]
请问 INTERNET 权限是做什么用的？

**Comment by lz233** [comment]
后期会实现一个「扩展」的功能，扩展需要联网请求，并返回给主程序结果

**Comment by linsui** [comment]
扩展是指扩展短链接吗？

**Comment by lz233** [comment]
你可以类比为chrome的扩展

**Comment by linsui** [comment]
请问扩展会托管在 GitHub 上吗？如果使用非自由的网络服务我就加个 NonFreeNet 标签。

**Comment by lz233** [comment]
扩展本身不提供网络服务，由用户自行导入dex，扩展内进行的网络请求由扩展的作者控制，我们没法控制

**Comment by linsui** [comment]
啊，明白了，Tarnhelm 只提供扩展加载功能但不提供扩展商店。谢谢。

**Comment by lz233** [comment]
需要注意的是，在构建时选择 fdroidRelease 变体，apk内是不会包含遥测服务的
别选错了（

**Comment by linsui** [comment]
:ok_hand: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11631 合并请求已经准备好了，没有问题就可以合并了。
