### ISSUE TITLE
[功能请求] 隐藏应用最近任务视图

### ISSUE THREAD

**Issue by jhqwqmc** [lz233/Tarnhelm#61]
锁定应用并且隐藏应用最近任务视图可以减少应用被误杀的问题

**Comment by lz233** [comment]
在原生系统下直接将 Tarnhelm 从最近任务视图划掉理论上不会产生问题，暂时不考虑国产 ROM 适配

**Comment by jhqwqmc** [comment]
> 在原生系统下直接将 Tarnhelm 从最近任务视图划掉理论上不会产生问题，暂时不考虑国产 ROM 适配

如果直接划掉会导致后台监听失效，感觉应该是应用划掉被关闭然后自启动没有弹出下面这个授权窗口导致无法正常读取剪切板产生的问题，如果能重新弹出这个窗口也可以解决这个问题

![Screenshot_2024-12-28-00-14-52-445_com android sy](https://github.com/user-attachments/assets/e6667106-7aff-46be-a350-1aea9d1113cd)

**Comment by lz233** [comment]
MIUI 的从后台把应用划掉就相当于 force-stop，这时候，应用是冷启动状态，是没有办法拉起这个弹窗的

**Comment by jhqwqmc** [comment]
刚才研究了一下只需要在这里加一个参数就可以解决了
https://github.com/lz233/Tarnhelm/blob/4fbd93e2e1c511c6e6bfab60457d1d91ea0771ea/app/src/main/AndroidManifest.xml#L33
改成
```xml
android:launchMode="singleTop"
android:excludeFromRecents="true">
```

**Comment by jhqwqmc** [comment]
这样就可以隐藏应用最近任务视图
