### ISSUE TITLE
Integrate "UntrackMe" rules

### ISSUE THREAD

**Issue by mochaaP** [lz233/Tarnhelm#8]
集成 [UntrackMe](https://framagit.org/tom79/nitterizeme) 的內建重定向規則。

- [ ] YouTube -> Invidious / Piped
- [ ] Twitter -> Nitter
- [ ] Instagram -> Bibliogram
- [ ] Reddit -> Teddit
- [ ] Medium -> Scribe.rip
- [ ] Wikipedia -> Wikileaks
- [ ] Google Maps -> OpenStreetMap
- [ ] TikTok -> ProxiTok

**Comment by lz233** [comment]
建议自行向 https://tarnhelm.project.ac.cn/rules.html 提  pr
另外，我也不是极端的隐私主义者，不太愿意牺牲用户体验换取极端隐私这样
